### PR TITLE
Set a default server icon

### PR DESCRIPTION
**Pull request by Insprill**
Adds a `server-icon.png` file of the PaperMake logo to the server directory when created to make it easier to find in server lists, and to make it look prettier.

This shouldn't conflict with any plugins, even ones that change the server icon, as that would override this just like a production server.

### CODE REVIEW

**Comment by Insprill** [comment]
@Rikonardo Is there any chance this, #7, #8, and #9 could be reviewed?

**Comment by Rikonardo** [comment]
Oh, sorry, had no time to review these PRs back then and forgot about them

As for this PR, it seems to me that icon file should only be created on the initial dev server setup, so that the user can delete or replace it with his own. You can determine whether the launch is initial setup, for example, by checking for the existence of the server.properties file (line 47 in DevServerTask.kt)

**Comment by Insprill** [comment]
Is that not what this does?

https://github.com/Insprill/PaperMake/blob/456a065160e62428f88350f5661303ba3ed16daa/src/main/kotlin/com/rikonardo/papermake/tasks/DevServerTask.kt#L78

**Comment by Rikonardo** [comment]
Well, it would allow user to change the icon but not remove it completely

**Comment by Insprill** [comment]
@Rikonardo I don't see the option to request a review so... I'm requesting a review :sweat_smile:

**Pull request merged**
